---
name: test

"on": [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: install
        run: |
          sudo apt-get update
          sudo apt-get install -y make yamllint
          npm ci
      - name: test
        run: make test
